# Generated by Django 3.0.7 on 2020-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0003_werewolf_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werewolf',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
