# Generated by Django 3.0.7 on 2020-08-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf', '0005_auto_20200707_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='werewolf',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
